apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-tweet-liker-deployment
spec:
  selector:
    matchLabels:
      app: auto-tweet-liker
  replicas: 1
  template:
    metadata:
      labels:
        app: auto-tweet-liker
    spec:
      containers:
        - name: auto-tweet-liker
          image: jamesquigley/auto-tweet-liker
          imagePullPolicy: Always
          volumeMounts:
            - name: auto-tweet-liker-secrets
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: auto-tweet-liker-secrets
          secret:
            secretName: auto-tweet-liker-secrets
