name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: docker build . --tag ${{ secrets.DOCKER_USERNAME }}/auto-tweet-liker
    - name: Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/auto-tweet-liker
