name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build
      run: docker build . --tag auto-tweet-liker
    - name: Push
      run: docker push auto-tweet-liker
